### ISSUE TITLE
How is the pool constructed in Sec.5 used in Sec.6 ?

### ISSUE THREAD

**Issue by exhyy** [thu-pacman/SmartMoE-AE#4]
Hi authors, thanks for your excellent works! 
I am confused about some details in the paper. In section 5, SmartMoE constructs a pool contains multiple execution plans, whose switching cost are moderate. However, in section 6, I find that both algorithm 1 and algorithm 2 are just focusing on the expert placement and their search spaces do not seem to be related to the pool constructed in section 5.

**Comment by zms1999** [comment]
Hi, as explained in Sec. 5.1, 
"we define a pool as a group of execution plans where expert placement is the only variable parallel strategy. "
Thus, we focus on how to find a proper expert placement plan in Sec. 6

**Comment by exhyy** [comment]
Could you please explain "expert placement is the only variable parallel strategy" in a more formal way, e.g, how is this pool related to the search space in Algo.1 and Algo.2? Could you please provide some examples of the pool constucted in Sec.5? Thank you!

**Comment by exhyy** [comment]
I just realized that Figure 4 presents a great example, which I had previously overlooked. Thank you again for your thoughtful response!
